sudo: required

language: php

services:
  - docker

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - docker build -t gazoapp/docker .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag gazoapp/docker:latest gazoapp/docker:$TRAVIS_TAG; fi && docker push gazoapp/docker

deploy:
  - provider: elasticbeanstalk
    app: gazoapp
    env: gazoapp-dev2
    region: us-west-2
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_KEY
    on:
      branch: master
