sudo: required

language: php

deploy:
  - provider: elasticbeanstalk
    app: gazoapp
    env: gazoapp-dev2
    bucket_name: $AWS_BUCKET_NAME
    region: us-west-2
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_KEY
    on:
      branch: master
