sudo: required

language: php

services:
  - docker

script:
  - ID=$(docker build -t gazoapp/docker .)
  - docker tag $ID gazoapp/docker:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push gazoapp/docker
