data:
  image: gazoapp/data
  volumes:
    - .:/data/www

web:
  image: gazoapp/php
  volumes_from:
    - data
  env_file: .env
  links:
    - db

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=gazoapp_docker
    - MYSQL_USER=gazoapp
    - MYSQL_PASSWORD=pass

phinx:
  image: gazoapp/phinx
  volumes_from:
    - data
  env_file: .env.phinx
  links:
    - db

composer:
  image: composer/composer
  volumes_from:
    - data
