web:
  build: .
  volumes:
    - .:/var/www/html
  env_file: .env
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=gazoapp_docker
    - MYSQL_USER=gazoapp
    - MYSQL_PASSWORD=pass
